# Generated by Django 4.0.6 on 2022-08-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_data',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
