# Generated by Django 4.0.6 on 2022-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_alter_admin_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_data',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
