# Generated by Django 4.0.6 on 2022-08-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_alter_admin_data_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
