# Generated by Django 4.0.6 on 2022-08-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_admin_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_blog',
            old_name='image',
            new_name='images',
        ),
        migrations.AddField(
            model_name='admin_blog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='admin_blog',
            name='desc1',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='admin_blog',
            name='wide_desc',
            field=models.TextField(default=2012),
            preserve_default=False,
        ),
    ]
