# Generated by Django 4.0.6 on 2022-08-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_alter_admin_blog_desc1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_blog',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
