# Generated by Django 4.0.6 on 2022-08-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0011_alter_admin_blog_desc1_alter_admin_blog_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_blog',
            old_name='desc1',
            new_name='desc',
        ),
    ]
